# docker-compose.yml
version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
  python-service:
    build: ./python-service
    ports:
      - "8000:8000"
